/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Discord: typeof import('./components/Discord.vue')['default']
    Favorites: typeof import('./components/Favorites.vue')['default']
    MusicPlayer: typeof import('./components/MusicPlayer.vue')['default']
    PlayHistory: typeof import('./components/PlayHistory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
